### ISSUE TITLE
missing pull-up/pull-down resistor settings for lFlags

### ISSUE THREAD

**Issue by itsermo** [jahudka/node-lgpio#1]
when creating an input or output pin, in the c library there are two functions:

`int lgGpioClaimInput(int handle, int lFlags, int gpio)`
`int lgGpioClaimOutput(int handle, int lFlags, int gpio, int level)`

where `lFlags` is an enum that has the following options:

`LG_SET_ACTIVE_LOW
LG_SET_OPEN_DRAIN
LG_SET_OPEN_SOURCE
LG_SET_PULL_UP
LG_SET_PULL_DOWN
LG_SET_PULL_NONE`

however the enum file generated by node-lgpio only shows the following:

`export declare enum GpioFlag {
    SET_ACTIVE_LOW = 4,
    SET_OPEN_DRAIN = 8,
    SET_OPEN_SOURCE = 16
}`

the 3 pull-up/pull-down settings are missing:

`LG_SET_PULL_UP
LG_SET_PULL_DOWN
LG_SET_PULL_NONE`

was the intention to leave out pull-up/pull-down functionality from the library?

Note that it also has implications on the return of the following function:
 
`int lgGpioGetMode(int handle, int gpio)`

which can return pull-up/pull-down info that corresponds to the enum as well. i think these are missing from the library as well.

**Comment by jahudka** [comment]
hey, thanks for reporting this & sorry for the delay! the missing flags have been added as of `v1.0.4`, published just now.

**Comment by leocata72** [comment]
Hi there, I don't understand in raspberry pi the output mode. In example on site  there is a sample code :
// open GPIO 31 for high output
status = lgGpioClaimOutput(h, 0, 31, 1);
but 0 isn't SET_ACTIVE_LOW or SET_OPEN_DRAIN  or SET_OPEN_SOURCE 
Can i use 0 but i don't understand the mode of port.
Thank you

**Comment by jahudka** [comment]
Hi @leocata72, I'm not entirely sure, it's been a while since I've worked on this, but I think that `0` would probably stand for the default output mode, which I would pretty much bet on being "active high". You could probably check that pretty easily on a breadboard using a LED and an adequate resistor. I won't have access to a Pi for the next week or so, so I can't check it myself right now, sorry 😢
